// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/contact': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contact.post').default>>>>
    }
    '/api/corretor/casas': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/corretor/casas.get').default>>>>
    }
    '/api/corretor/dashboard': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/corretor/dashboard.get').default>>>>
    }
    '/api/corretor/leads': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/corretor/leads.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/corretor/leads.post').default>>>>
    }
    '/api/user-data/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user-data/delete.post').default>>>>
    }
    '/api/visits/instant': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/visits/instant.post').default>>>>
    }
    '/api/visits/qr/:code': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/visits/qr/[code].get').default>>>>
    }
    '/api/visits/schedule': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/visits/schedule.post').default>>>>
    }
    '/api/visits/verify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/visits/verify.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}