// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/9/2026, 9:12:14 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/rbonon/Documents/GitHub/fortegb/Sandbox/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rbonon/Documents/GitHub/fortegb/Sandbox/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rbonon/Documents/GitHub/fortegb/Sandbox/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rbonon/Documents/GitHub/fortegb/Sandbox/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rbonon/Documents/GitHub/fortegb/Sandbox/plugins/**/*.{js,ts,mjs}","/Users/rbonon/Documents/GitHub/fortegb/Sandbox/composables/**/*.{js,ts,mjs}","/Users/rbonon/Documents/GitHub/fortegb/Sandbox/utils/**/*.{js,ts,mjs}","/Users/rbonon/Documents/GitHub/fortegb/Sandbox/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rbonon/Documents/GitHub/fortegb/Sandbox/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/rbonon/Documents/GitHub/fortegb/Sandbox/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/rbonon/Documents/GitHub/fortegb/Sandbox/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;